version: "3.9"

services:
  bot:
    working_dir: /app
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python /testing_bot/bot.py"      
    env_file: .env